# Generated by Django 4.2.11 on 2026-03-12 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerguruanTinggi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pt', models.CharField(max_length=20, unique=True, verbose_name='Kode PT')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama PT')),
                ('singkatan', models.CharField(max_length=20, verbose_name='Singkatan')),
                ('jenis', models.CharField(choices=[('universitas', 'Universitas'), ('institut', 'Institut'), ('sekolah_tinggi', 'Sekolah Tinggi'), ('politeknik', 'Politeknik'), ('akademi', 'Akademi')], max_length=20, verbose_name='Jenis PT')),
                ('organisasi_induk', models.CharField(choices=[('muhammadiyah', 'Muhammadiyah'), ('aisyiyah', 'Aisyiyah')], max_length=20, verbose_name='Organisasi Induk')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('kota', models.CharField(max_length=100, verbose_name='Kota/Kabupaten')),
                ('provinsi', models.CharField(max_length=100, verbose_name='Provinsi')),
                ('kode_pos', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telepon', models.CharField(blank=True, max_length=20, verbose_name='Telepon')),
                ('akreditasi_institusi', models.CharField(choices=[('unggul', 'Unggul'), ('baik_sekali', 'Baik Sekali'), ('baik', 'Baik'), ('belum', 'Belum Terakreditasi')], default='belum', max_length=20, verbose_name='Akreditasi Institusi')),
                ('nomor_sk_akreditasi', models.CharField(blank=True, max_length=100)),
                ('tanggal_sk_akreditasi', models.DateField(blank=True, null=True)),
                ('tanggal_kadaluarsa_akreditasi', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tahun_berdiri', models.PositiveIntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perguruan Tinggi',
                'verbose_name_plural': 'Perguruan Tinggi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Wilayah',
                'verbose_name_plural': 'Wilayah',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(max_length=20, verbose_name='Kode Prodi')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Program Studi')),
                ('jenjang', models.CharField(choices=[('d1', 'Diploma 1'), ('d2', 'Diploma 2'), ('d3', 'Diploma 3'), ('d4', 'Diploma 4 / Sarjana Terapan'), ('s1', 'Sarjana (S1)'), ('profesi', 'Profesi'), ('s2', 'Magister (S2)'), ('s3', 'Doktor (S3)')], max_length=10)),
                ('akreditasi', models.CharField(choices=[('unggul', 'Unggul'), ('baik_sekali', 'Baik Sekali'), ('baik', 'Baik'), ('c', 'C'), ('belum', 'Belum Terakreditasi')], default='belum', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perguruan_tinggi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_studi', to='universities.perguruantinggi')),
            ],
            options={
                'verbose_name': 'Program Studi',
                'verbose_name_plural': 'Program Studi',
                'ordering': ['nama'],
                'unique_together': {('perguruan_tinggi', 'kode_prodi')},
            },
        ),
        migrations.AddField(
            model_name='perguruantinggi',
            name='wilayah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguruan_tinggi', to='universities.wilayah'),
        ),
        migrations.CreateModel(
            name='DataMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=10, verbose_name='Tahun Akademik')),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], max_length=10)),
                ('mahasiswa_baru', models.PositiveIntegerField(default=0)),
                ('mahasiswa_aktif', models.PositiveIntegerField(default=0)),
                ('mahasiswa_lulus', models.PositiveIntegerField(default=0)),
                ('mahasiswa_dropout', models.PositiveIntegerField(default=0)),
                ('mahasiswa_pria', models.PositiveIntegerField(default=0)),
                ('mahasiswa_wanita', models.PositiveIntegerField(default=0)),
                ('perguruan_tinggi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_mahasiswa', to='universities.perguruantinggi')),
                ('program_studi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_mahasiswa', to='universities.programstudi')),
            ],
            options={
                'verbose_name': 'Data Mahasiswa',
                'verbose_name_plural': 'Data Mahasiswa',
                'ordering': ['-tahun_akademik', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='DataDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField()),
                ('dosen_tetap', models.PositiveIntegerField(default=0)),
                ('dosen_tidak_tetap', models.PositiveIntegerField(default=0)),
                ('dosen_s3', models.PositiveIntegerField(default=0)),
                ('dosen_s2', models.PositiveIntegerField(default=0)),
                ('dosen_s1', models.PositiveIntegerField(default=0)),
                ('dosen_guru_besar', models.PositiveIntegerField(default=0)),
                ('dosen_lektor_kepala', models.PositiveIntegerField(default=0)),
                ('dosen_lektor', models.PositiveIntegerField(default=0)),
                ('dosen_asisten_ahli', models.PositiveIntegerField(default=0)),
                ('dosen_bersertifikat', models.PositiveIntegerField(default=0)),
                ('perguruan_tinggi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_dosen', to='universities.perguruantinggi')),
            ],
            options={
                'verbose_name': 'Data Dosen',
                'verbose_name_plural': 'Data Dosen',
                'ordering': ['-tahun'],
                'unique_together': {('perguruan_tinggi', 'tahun')},
            },
        ),
    ]
