# Generated by Django 4.2.11 on 2026-03-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_datadosen_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstudi',
            name='no_sk_akreditasi',
            field=models.CharField(blank=True, max_length=100, verbose_name='No. SK Akreditasi'),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='tanggal_kedaluarsa_akreditasi',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Kedaluarsa Akreditasi'),
        ),
    ]
