# Generated by Django 4.2.11 on 2026-03-19 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_add_sk_akreditasi_programstudi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='NIDN')),
                ('nuptk', models.CharField(blank=True, max_length=20, verbose_name='NUPTK')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Dosen')),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('program_studi_nama', models.CharField(blank=True, max_length=200, verbose_name='Nama Prodi (PDDikti)')),
                ('jabatan_fungsional', models.CharField(blank=True, max_length=50, verbose_name='Jabatan Fungsional')),
                ('pendidikan_tertinggi', models.CharField(blank=True, choices=[('s1', 'S1'), ('s2', 'S2'), ('s3', 'S3'), ('profesi', 'Profesi'), ('lainnya', 'Lainnya')], max_length=10, verbose_name='Pendidikan Tertinggi')),
                ('ikatan_kerja', models.CharField(blank=True, choices=[('tetap', 'Dosen Tetap'), ('tidak_tetap', 'Dosen Tidak Tetap')], max_length=15, verbose_name='Ikatan Kerja')),
                ('status', models.CharField(blank=True, max_length=30, verbose_name='Status')),
                ('url_pencarian', models.CharField(blank=True, max_length=500, verbose_name='URL Pencarian')),
                ('scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Scrape')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perguruan_tinggi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_dosen', to='universities.perguruantinggi', verbose_name='Perguruan Tinggi')),
                ('program_studi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_dosen', to='universities.programstudi', verbose_name='Program Studi')),
            ],
            options={
                'verbose_name': 'Profil Dosen',
                'verbose_name_plural': 'Profil Dosen',
                'ordering': ['nama'],
                'indexes': [models.Index(fields=['nidn'], name='universitie_nidn_22dae8_idx'), models.Index(fields=['nuptk'], name='universitie_nuptk_93c04f_idx'), models.Index(fields=['perguruan_tinggi', 'program_studi'], name='universitie_perguru_71c930_idx')],
                'unique_together': {('perguruan_tinggi', 'nidn')},
            },
        ),
    ]
