# Generated by Django 4.2.11 on 2026-03-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_profildosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profildosen',
            name='nidn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='NIDN'),
        ),
    ]
