# Generated by Django 4.2.11 on 2026-03-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_alter_profildosen_nidn'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPendidikanDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguruan_tinggi_asal', models.CharField(blank=True, max_length=300, verbose_name='Perguruan Tinggi Asal')),
                ('gelar', models.CharField(blank=True, max_length=150, verbose_name='Gelar Akademik')),
                ('jenjang', models.CharField(blank=True, max_length=20, verbose_name='Jenjang')),
                ('tahun_lulus', models.CharField(blank=True, max_length=4, verbose_name='Tahun Lulus')),
                ('profil_dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pendidikan', to='universities.profildosen', verbose_name='Profil Dosen')),
            ],
            options={
                'verbose_name': 'Riwayat Pendidikan Dosen',
                'verbose_name_plural': 'Riwayat Pendidikan Dosen',
                'ordering': ['profil_dosen__nama', 'tahun_lulus'],
                'indexes': [models.Index(fields=['profil_dosen'], name='universitie_profil__e543aa_idx'), models.Index(fields=['jenjang'], name='universitie_jenjang_4946fc_idx')],
            },
        ),
    ]
