# Generated by Django 4.2.11 on 2026-03-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_riwayat_pendidikan_dosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatpendidikandosen',
            name='is_luar_negeri',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Luar Negeri'),
        ),
        migrations.AddIndex(
            model_name='riwayatpendidikandosen',
            index=models.Index(fields=['jenjang', 'is_luar_negeri'], name='universitie_jenjang_2162cb_idx'),
        ),
    ]
