# Generated by Django 4.2.11 on 2026-03-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_riwayat_pendidikan_is_luar_negeri'),
    ]

    operations = [
        migrations.CreateModel(
            name='SintaAfiliasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinta_id', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='SINTA ID')),
                ('sinta_kode', models.CharField(blank=True, max_length=20, verbose_name='Kode SINTA')),
                ('nama_sinta', models.CharField(blank=True, max_length=200, verbose_name='Nama di SINTA')),
                ('singkatan_sinta', models.CharField(blank=True, max_length=50, verbose_name='Singkatan di SINTA')),
                ('lokasi_sinta', models.CharField(blank=True, max_length=200, verbose_name='Lokasi di SINTA')),
                ('sinta_profile_url', models.URLField(blank=True, verbose_name='URL Profil SINTA')),
                ('logo_base64', models.TextField(blank=True, verbose_name='Logo Universitas (Base64)')),
                ('jumlah_authors', models.PositiveIntegerField(default=0, verbose_name='Jumlah Authors')),
                ('jumlah_departments', models.PositiveIntegerField(default=0, verbose_name='Jumlah Departments')),
                ('jumlah_journals', models.PositiveIntegerField(default=0, verbose_name='Jumlah Journals')),
                ('sinta_score_overall', models.BigIntegerField(default=0, verbose_name='SINTA Score Overall')),
                ('sinta_score_3year', models.BigIntegerField(default=0, verbose_name='SINTA Score 3Yr')),
                ('sinta_score_productivity', models.IntegerField(default=0, verbose_name='SINTA Score Productivity')),
                ('sinta_score_productivity_3year', models.IntegerField(default=0, verbose_name='SINTA Score Productivity 3Yr')),
                ('scopus_dokumen', models.FloatField(default=0, verbose_name='Scopus Documents')),
                ('scopus_sitasi', models.FloatField(default=0, verbose_name='Scopus Citations')),
                ('scopus_dokumen_disitasi', models.FloatField(default=0, verbose_name='Scopus Cited Documents')),
                ('scopus_sitasi_per_peneliti', models.FloatField(default=0, verbose_name='Scopus Citation per Researcher')),
                ('gscholar_dokumen', models.FloatField(default=0, verbose_name='GScholar Documents')),
                ('gscholar_sitasi', models.FloatField(default=0, verbose_name='GScholar Citations')),
                ('gscholar_dokumen_disitasi', models.FloatField(default=0, verbose_name='GScholar Cited Documents')),
                ('gscholar_sitasi_per_peneliti', models.FloatField(default=0, verbose_name='GScholar Citation per Researcher')),
                ('wos_dokumen', models.FloatField(default=0, verbose_name='WoS Documents')),
                ('wos_sitasi', models.FloatField(default=0, verbose_name='WoS Citations')),
                ('wos_dokumen_disitasi', models.FloatField(default=0, verbose_name='WoS Cited Documents')),
                ('wos_sitasi_per_peneliti', models.FloatField(default=0, verbose_name='WoS Citation per Researcher')),
                ('garuda_dokumen', models.FloatField(default=0, verbose_name='Garuda Documents')),
                ('garuda_sitasi', models.FloatField(default=0, verbose_name='Garuda Citations')),
                ('garuda_dokumen_disitasi', models.FloatField(default=0, verbose_name='Garuda Cited Documents')),
                ('garuda_sitasi_per_peneliti', models.FloatField(default=0, verbose_name='Garuda Citation per Researcher')),
                ('scopus_q1', models.PositiveIntegerField(default=0, verbose_name='Scopus Q1')),
                ('scopus_q2', models.PositiveIntegerField(default=0, verbose_name='Scopus Q2')),
                ('scopus_q3', models.PositiveIntegerField(default=0, verbose_name='Scopus Q3')),
                ('scopus_q4', models.PositiveIntegerField(default=0, verbose_name='Scopus Q4')),
                ('scopus_noq', models.PositiveIntegerField(default=0, verbose_name='Scopus No-Q')),
                ('sinta_last_update', models.CharField(blank=True, max_length=50, verbose_name='Last Update SINTA')),
                ('scraped_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Scrape')),
                ('perguruan_tinggi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sinta_afiliasi', to='universities.perguruantinggi', verbose_name='Perguruan Tinggi')),
            ],
            options={
                'verbose_name': 'SINTA Afiliasi',
                'verbose_name_plural': 'SINTA Afiliasi',
                'ordering': ['-sinta_score_overall'],
                'indexes': [models.Index(fields=['sinta_id'], name='universitie_sinta_i_a400d1_idx'), models.Index(fields=['sinta_score_overall'], name='universitie_sinta_s_6c30f6_idx')],
            },
        ),
    ]
