# Generated by Django 4.2.11 on 2026-03-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_sinta_afiliasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SintaCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(blank=True, choices=[('Cluster Mandiri', 'Cluster Mandiri'), ('Cluster Utama', 'Cluster Utama'), ('Cluster Madya', 'Cluster Madya'), ('Cluster Pratama', 'Cluster Pratama'), ('Cluster Binaan', 'Cluster Binaan')], db_index=True, max_length=30, verbose_name='Nama Cluster')),
                ('total_score', models.FloatField(default=0, verbose_name='Total Score')),
                ('score_publication', models.FloatField(default=0, verbose_name='Score Publication (25%)')),
                ('score_hki', models.FloatField(default=0, verbose_name='Score HKI (10%)')),
                ('score_kelembagaan', models.FloatField(default=0, verbose_name='Score Kelembagaan (15%)')),
                ('score_research', models.FloatField(default=0, verbose_name='Score Research (15%)')),
                ('score_community_service', models.FloatField(default=0, verbose_name='Score Community Service (15%)')),
                ('score_sdm', models.FloatField(default=0, verbose_name='Score SDM (15%)')),
                ('ternormal_publication', models.FloatField(default=0, verbose_name='Ternormal Publication')),
                ('ternormal_hki', models.FloatField(default=0, verbose_name='Ternormal HKI')),
                ('ternormal_kelembagaan', models.FloatField(default=0, verbose_name='Ternormal Kelembagaan')),
                ('ternormal_research', models.FloatField(default=0, verbose_name='Ternormal Research')),
                ('ternormal_community_service', models.FloatField(default=0, verbose_name='Ternormal Community Service')),
                ('ternormal_sdm', models.FloatField(default=0, verbose_name='Ternormal SDM')),
                ('periode', models.CharField(default='2022-2024', max_length=20, verbose_name='Periode Penilaian')),
                ('scraped_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Scrape')),
                ('afiliasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='universities.sintaafiliasi', verbose_name='SINTA Afiliasi')),
            ],
            options={
                'verbose_name': 'SINTA Cluster',
                'verbose_name_plural': 'SINTA Cluster',
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='SintaWcuTahunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('arts_humanities', models.PositiveIntegerField(default=0, verbose_name='Arts & Humanities')),
                ('engineering_technology', models.PositiveIntegerField(default=0, verbose_name='Engineering & Technology')),
                ('life_sciences_medicine', models.PositiveIntegerField(default=0, verbose_name='Life Sciences & Medicine')),
                ('natural_sciences', models.PositiveIntegerField(default=0, verbose_name='Natural Sciences')),
                ('social_sciences_management', models.PositiveIntegerField(default=0, verbose_name='Social Sciences & Management')),
                ('overall', models.PositiveIntegerField(default=0, verbose_name='Overall')),
                ('afiliasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wcu_tahunan', to='universities.sintaafiliasi', verbose_name='SINTA Afiliasi')),
            ],
            options={
                'verbose_name': 'SINTA WCU Tahunan',
                'verbose_name_plural': 'SINTA WCU Tahunan',
                'ordering': ['afiliasi', 'tahun'],
                'indexes': [models.Index(fields=['tahun'], name='universitie_tahun_e8b1ec_idx')],
                'unique_together': {('afiliasi', 'tahun')},
            },
        ),
        migrations.CreateModel(
            name='SintaTrendTahunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('scopus', 'Publikasi Scopus'), ('research', 'Penelitian'), ('service', 'Pengabdian Masyarakat')], max_length=10, verbose_name='Jenis')),
                ('tahun', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('jumlah', models.PositiveIntegerField(default=0, verbose_name='Jumlah')),
                ('research_article', models.PositiveIntegerField(default=0, verbose_name='Research Article')),
                ('research_conference', models.PositiveIntegerField(default=0, verbose_name='Research Conference')),
                ('research_others', models.PositiveIntegerField(default=0, verbose_name='Research Others')),
                ('afiliasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_tahunan', to='universities.sintaafiliasi', verbose_name='SINTA Afiliasi')),
            ],
            options={
                'verbose_name': 'SINTA Trend Tahunan',
                'verbose_name_plural': 'SINTA Trend Tahunan',
                'ordering': ['afiliasi', 'jenis', 'tahun'],
                'indexes': [models.Index(fields=['jenis', 'tahun'], name='universitie_jenis_d323f2_idx')],
                'unique_together': {('afiliasi', 'jenis', 'tahun')},
            },
        ),
        migrations.CreateModel(
            name='SintaClusterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, verbose_name='Kode Item')),
                ('section', models.CharField(max_length=30, verbose_name='Seksi')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Item')),
                ('bobot', models.FloatField(default=0, verbose_name='Bobot')),
                ('nilai', models.FloatField(default=0, verbose_name='Nilai (dinormalisasi)')),
                ('total', models.FloatField(default=0, verbose_name='Total (nilai × bobot)')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='universities.sintacluster', verbose_name='Cluster')),
            ],
            options={
                'verbose_name': 'SINTA Cluster Item',
                'verbose_name_plural': 'SINTA Cluster Items',
                'ordering': ['cluster', 'section', 'kode'],
                'indexes': [models.Index(fields=['kode'], name='universitie_kode_8664b6_idx')],
                'unique_together': {('cluster', 'kode')},
            },
        ),
        migrations.AddIndex(
            model_name='sintacluster',
            index=models.Index(fields=['cluster_name'], name='universitie_cluster_f6dbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='sintacluster',
            index=models.Index(fields=['total_score'], name='universitie_total_s_075479_idx'),
        ),
    ]
