# Generated by Django 4.2.11 on 2026-03-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_sintacluster_sintawcutahunan_sintatrendtahunan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SintaJurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinta_id', models.PositiveIntegerField(unique=True, verbose_name='SINTA ID Jurnal')),
                ('nama', models.CharField(max_length=300, verbose_name='Nama Jurnal')),
                ('p_issn', models.CharField(blank=True, max_length=20, verbose_name='P-ISSN')),
                ('e_issn', models.CharField(blank=True, max_length=20, verbose_name='E-ISSN')),
                ('akreditasi', models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], db_index=True, max_length=2, verbose_name='Akreditasi')),
                ('subject_area', models.CharField(blank=True, max_length=200, verbose_name='Subject Area')),
                ('afiliasi_teks', models.CharField(blank=True, max_length=300, verbose_name='Afiliasi (teks)')),
                ('impact', models.FloatField(default=0, verbose_name='Impact')),
                ('h5_index', models.PositiveIntegerField(default=0, verbose_name='H5-Index')),
                ('sitasi_5yr', models.PositiveIntegerField(default=0, verbose_name='Sitasi 5 Tahun')),
                ('sitasi_total', models.PositiveIntegerField(default=0, verbose_name='Sitasi Total')),
                ('is_scopus', models.BooleanField(default=False, verbose_name='Scopus Indexed')),
                ('is_garuda', models.BooleanField(default=False, verbose_name='Garuda Indexed')),
                ('url_website', models.CharField(blank=True, max_length=500, verbose_name='URL Website')),
                ('url_scholar', models.CharField(blank=True, max_length=500, verbose_name='URL Google Scholar')),
                ('url_editor', models.CharField(blank=True, max_length=500, verbose_name='URL Editor')),
                ('url_garuda', models.CharField(blank=True, max_length=500, verbose_name='URL Garuda')),
                ('logo_base64', models.TextField(blank=True, verbose_name='Logo (Base64)')),
                ('scraped_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Scrape')),
                ('perguruan_tinggi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal_sinta', to='universities.perguruantinggi', verbose_name='Perguruan Tinggi')),
            ],
            options={
                'verbose_name': 'SINTA Jurnal',
                'verbose_name_plural': 'SINTA Jurnal',
                'ordering': ['-impact'],
                'indexes': [models.Index(fields=['akreditasi'], name='universitie_akredit_48cf0e_idx'), models.Index(fields=['perguruan_tinggi', 'akreditasi'], name='universitie_perguru_3af7bd_idx')],
            },
        ),
    ]
