# Generated by Django 4.2.11 on 2026-03-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0010_sintajurnal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintajurnal',
            name='wcu_area',
            field=models.CharField(blank=True, help_text='Kelompok bidang sesuai standar WCU/QS (diisi manual atau ML)', max_length=200, verbose_name='WCU Subject Area'),
        ),
        migrations.AlterField(
            model_name='sintajurnal',
            name='subject_area',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subject Area (SINTA)'),
        ),
    ]
