# Generated by Django 4.2.11 on 2026-03-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0011_add_wcu_area_to_sintajurnal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SintaDepartemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=300, verbose_name='Nama Departemen')),
                ('jenjang', models.CharField(blank=True, max_length=10, verbose_name='Jenjang (S1/S2/S3/D3)')),
                ('kode_dept', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Kode Departemen SINTA')),
                ('url_profil', models.URLField(blank=True, max_length=500, verbose_name='URL Profil SINTA')),
                ('sinta_score_overall', models.BigIntegerField(default=0, verbose_name='SINTA Score Overall')),
                ('sinta_score_3year', models.BigIntegerField(default=0, verbose_name='SINTA Score 3Yr')),
                ('jumlah_authors', models.PositiveIntegerField(default=0, verbose_name='Jumlah Authors')),
                ('scraped_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Scrape')),
                ('afiliasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departemen', to='universities.sintaafiliasi', verbose_name='SINTA Afiliasi')),
            ],
            options={
                'verbose_name': 'SINTA Departemen',
                'verbose_name_plural': 'SINTA Departemen',
                'ordering': ['-sinta_score_overall'],
                'indexes': [models.Index(fields=['afiliasi', 'jenjang'], name='universitie_afilias_cf4cf7_idx'), models.Index(fields=['sinta_score_overall'], name='universitie_sinta_s_5c05b2_idx')],
                'unique_together': {('afiliasi', 'kode_dept')},
            },
        ),
    ]
