# Generated by Django 4.2.11 on 2026-03-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0012_add_sintadepartemen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SintaAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinta_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='SINTA ID Author')),
                ('nama', models.CharField(max_length=300, verbose_name='Nama Author')),
                ('url_profil', models.URLField(blank=True, max_length=500, verbose_name='URL Profil SINTA')),
                ('foto_url', models.URLField(blank=True, max_length=500, verbose_name='URL Foto')),
                ('bidang_keilmuan', models.JSONField(blank=True, default=list, verbose_name='Bidang Keilmuan')),
                ('sinta_score_overall', models.BigIntegerField(default=0, verbose_name='SINTA Score Overall')),
                ('sinta_score_3year', models.BigIntegerField(default=0, verbose_name='SINTA Score 3Yr')),
                ('affil_score', models.BigIntegerField(default=0, verbose_name='Affil Score')),
                ('affil_score_3year', models.BigIntegerField(default=0, verbose_name='Affil Score 3Yr')),
                ('scopus_artikel', models.IntegerField(default=0)),
                ('scopus_sitasi', models.IntegerField(default=0)),
                ('scopus_cited_doc', models.IntegerField(default=0)),
                ('scopus_h_index', models.SmallIntegerField(default=0)),
                ('scopus_i10_index', models.SmallIntegerField(default=0)),
                ('scopus_g_index', models.SmallIntegerField(default=0)),
                ('gscholar_artikel', models.IntegerField(default=0)),
                ('gscholar_sitasi', models.IntegerField(default=0)),
                ('gscholar_cited_doc', models.IntegerField(default=0)),
                ('gscholar_h_index', models.SmallIntegerField(default=0)),
                ('gscholar_i10_index', models.SmallIntegerField(default=0)),
                ('gscholar_g_index', models.SmallIntegerField(default=0)),
                ('wos_artikel', models.IntegerField(default=0)),
                ('wos_sitasi', models.IntegerField(default=0)),
                ('wos_cited_doc', models.IntegerField(default=0)),
                ('wos_h_index', models.SmallIntegerField(default=0)),
                ('wos_i10_index', models.SmallIntegerField(default=0)),
                ('wos_g_index', models.SmallIntegerField(default=0)),
                ('scopus_q1', models.PositiveIntegerField(default=0)),
                ('scopus_q2', models.PositiveIntegerField(default=0)),
                ('scopus_q3', models.PositiveIntegerField(default=0)),
                ('scopus_q4', models.PositiveIntegerField(default=0)),
                ('scopus_noq', models.PositiveIntegerField(default=0)),
                ('research_conference', models.IntegerField(default=0)),
                ('research_articles', models.IntegerField(default=0)),
                ('research_others', models.IntegerField(default=0)),
                ('scraped_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Scrape')),
                ('afiliasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='universities.sintaafiliasi', verbose_name='SINTA Afiliasi')),
                ('departemen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='universities.sintadepartemen', verbose_name='Departemen')),
            ],
            options={
                'verbose_name': 'SINTA Author',
                'verbose_name_plural': 'SINTA Author',
                'ordering': ['-sinta_score_overall'],
            },
        ),
        migrations.CreateModel(
            name='SintaAuthorTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('scopus', 'Publikasi Scopus'), ('research', 'Penelitian'), ('service', 'Pengabdian')], max_length=10, verbose_name='Jenis')),
                ('tahun', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('jumlah', models.PositiveIntegerField(default=0, verbose_name='Jumlah')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend', to='universities.sintaauthor', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'SINTA Author Trend',
                'verbose_name_plural': 'SINTA Author Trend',
                'ordering': ['author', 'jenis', 'tahun'],
                'indexes': [models.Index(fields=['jenis', 'tahun'], name='universitie_jenis_e99f00_idx')],
                'unique_together': {('author', 'jenis', 'tahun')},
            },
        ),
        migrations.AddIndex(
            model_name='sintaauthor',
            index=models.Index(fields=['sinta_score_overall'], name='universitie_sinta_s_05797e_idx'),
        ),
        migrations.AddIndex(
            model_name='sintaauthor',
            index=models.Index(fields=['afiliasi'], name='universitie_afilias_92fe85_idx'),
        ),
        migrations.AddIndex(
            model_name='sintaauthor',
            index=models.Index(fields=['departemen'], name='universitie_departe_655498_idx'),
        ),
    ]
