# Generated by Django 4.2.11 on 2026-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0013_add_sintaauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintadepartemen',
            name='gscholar_artikel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='gscholar_sitasi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='research_articles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='research_conference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='research_others',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='scopus_artikel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='scopus_noq',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='scopus_q1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='scopus_q2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='scopus_q3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='scopus_q4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='scopus_sitasi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='sinta_score_productivity',
            field=models.IntegerField(default=0, verbose_name='SINTA Score Productivity'),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='sinta_score_productivity_3year',
            field=models.IntegerField(default=0, verbose_name='SINTA Score Productivity 3Yr'),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='trend_scopus',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='wos_artikel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sintadepartemen',
            name='wos_sitasi',
            field=models.IntegerField(default=0),
        ),
    ]
