# Generated by Django 4.2.11 on 2026-03-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0014_add_dept_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SintaAuthorPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber', models.CharField(choices=[('gscholar', 'Google Scholar'), ('scopus', 'Scopus'), ('wos', 'Web of Science')], max_length=10, verbose_name='Sumber')),
                ('pub_id', models.CharField(db_index=True, max_length=200, verbose_name='ID Publikasi')),
                ('judul', models.CharField(max_length=1000, verbose_name='Judul')),
                ('penulis', models.TextField(blank=True, verbose_name='Penulis')),
                ('jurnal', models.CharField(blank=True, max_length=500, verbose_name='Jurnal / Venue')),
                ('tahun', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tahun')),
                ('sitasi', models.PositiveIntegerField(default=0, verbose_name='Jumlah Sitasi')),
                ('url', models.URLField(blank=True, max_length=800, verbose_name='URL')),
                ('scraped_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Scrape')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='universities.sintaauthor', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'SINTA Author Publication',
                'verbose_name_plural': 'SINTA Author Publications',
                'ordering': ['-sitasi', '-tahun'],
                'indexes': [models.Index(fields=['author', 'sumber'], name='universitie_author__081f42_idx'), models.Index(fields=['tahun'], name='universitie_tahun_7d59d2_idx')],
                'unique_together': {('author', 'sumber', 'pub_id')},
            },
        ),
        migrations.CreateModel(
            name='SintaAuthorCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber', models.CharField(choices=[('gscholar', 'Google Scholar'), ('scopus', 'Scopus')], max_length=10, verbose_name='Sumber')),
                ('cite_id', models.CharField(db_index=True, max_length=200, verbose_name='ID Sitasi')),
                ('judul', models.CharField(max_length=1000, verbose_name='Judul Karya Pensitasi')),
                ('penulis', models.TextField(blank=True, verbose_name='Penulis')),
                ('jurnal', models.CharField(blank=True, max_length=500, verbose_name='Jurnal / Venue')),
                ('tahun', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tahun')),
                ('url', models.URLField(blank=True, max_length=800, verbose_name='URL')),
                ('scraped_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Scrape')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='universities.sintaauthor', verbose_name='Author Disitasi')),
            ],
            options={
                'verbose_name': 'SINTA Author Citation',
                'verbose_name_plural': 'SINTA Author Citations',
                'ordering': ['-tahun'],
                'indexes': [models.Index(fields=['author', 'sumber'], name='universitie_author__3166ba_idx'), models.Index(fields=['tahun'], name='universitie_tahun_a1467b_idx')],
                'unique_together': {('author', 'sumber', 'cite_id')},
            },
        ),
    ]
