# Generated by Django 4.2.11 on 2026-03-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0015_add_sintaauthor_publication_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintaauthortrend',
            name='jenis',
            field=models.CharField(choices=[('scopus', 'Publikasi Scopus'), ('research', 'Penelitian'), ('service', 'Pengabdian'), ('gscholar_pub', 'Publikasi Google Scholar'), ('gscholar_cite', 'Sitasi Google Scholar')], max_length=20, verbose_name='Jenis'),
        ),
    ]
