# Generated by Django 4.2.11 on 2026-03-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0017_add_scopus_artikel_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='RisetAnalisisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('data', models.JSONField(verbose_name='Data hasil analisis')),
            ],
            options={
                'verbose_name': 'Riset Analisis Snapshot',
                'verbose_name_plural': 'Riset Analisis Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='sintascopusartikelauthor',
            name='uniq_scopus_artikel_author',
        ),
        migrations.RenameIndex(
            model_name='sintascopusartikel',
            new_name='universitie_tahun_325c39_idx',
            old_name='univ_scopus_tahun_idx',
        ),
        migrations.RenameIndex(
            model_name='sintascopusartikel',
            new_name='universitie_kuartil_344131_idx',
            old_name='univ_scopus_kuartil_idx',
        ),
        migrations.RenameIndex(
            model_name='sintascopusartikelauthor',
            new_name='universitie_author__0636ed_idx',
            old_name='univ_scopus_author_idx',
        ),
        migrations.AlterUniqueTogether(
            name='sintascopusartikelauthor',
            unique_together={('artikel', 'author')},
        ),
    ]
