# Generated by Django 4.2.11 on 2026-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0018_add_riset_analisis_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RisetLdaDeskripsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True, verbose_name='Label Topik')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi AI')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
            ],
            options={
                'verbose_name': 'LDA Deskripsi',
                'verbose_name_plural': 'LDA Deskripsi',
                'ordering': ['label'],
            },
        ),
    ]
