# Generated by Django 4.2.11 on 2026-03-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0019_add_riset_lda_deskripsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SintaPenelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=1000, verbose_name='Judul Penelitian')),
                ('leader_nama', models.CharField(blank=True, max_length=200, verbose_name='Nama Ketua')),
                ('skema', models.CharField(blank=True, max_length=300, verbose_name='Skema Penelitian')),
                ('skema_kode', models.CharField(blank=True, max_length=20, verbose_name='Kode Skema')),
                ('tahun', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tahun')),
                ('dana', models.CharField(blank=True, max_length=50, verbose_name='Dana')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Status')),
                ('sumber', models.CharField(blank=True, max_length=50, verbose_name='Sumber Dana')),
                ('scraped_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Scrape')),
            ],
            options={
                'verbose_name': 'Sinta Penelitian',
                'verbose_name_plural': 'Sinta Penelitian',
                'ordering': ['-tahun', 'judul'],
            },
        ),
        migrations.CreateModel(
            name='SintaPenelitianAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False, verbose_name='Ketua')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penelitians', to='universities.sintaauthor', verbose_name='Author')),
                ('penelitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penelitian_authors', to='universities.sintapenelitian', verbose_name='Penelitian')),
            ],
            options={
                'verbose_name': 'Sinta Penelitian Author',
                'verbose_name_plural': 'Sinta Penelitian Authors',
            },
        ),
        migrations.AddIndex(
            model_name='sintapenelitian',
            index=models.Index(fields=['tahun'], name='universitie_tahun_02fba8_idx'),
        ),
        migrations.AddIndex(
            model_name='sintapenelitian',
            index=models.Index(fields=['skema_kode'], name='universitie_skema_k_ddbf70_idx'),
        ),
        migrations.AddIndex(
            model_name='sintapenelitian',
            index=models.Index(fields=['sumber'], name='universitie_sumber_a7b72a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sintapenelitian',
            unique_together={('judul', 'tahun', 'skema_kode')},
        ),
        migrations.AddIndex(
            model_name='sintapenelitianauthor',
            index=models.Index(fields=['author'], name='universitie_author__9edff7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sintapenelitianauthor',
            unique_together={('penelitian', 'author')},
        ),
    ]
