# Generated by Django 4.2.11 on 2026-03-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0020_add_sinta_penelitian_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SintaPengabdian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=1000, verbose_name='Judul Pengabdian')),
                ('leader_nama', models.CharField(blank=True, max_length=200, verbose_name='Nama Ketua')),
                ('skema', models.CharField(blank=True, max_length=300, verbose_name='Skema Pengabdian')),
                ('skema_kode', models.CharField(blank=True, max_length=20, verbose_name='Kode Skema')),
                ('tahun', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tahun')),
                ('dana', models.CharField(blank=True, max_length=50, verbose_name='Dana')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Status')),
                ('sumber', models.CharField(blank=True, max_length=50, verbose_name='Sumber Dana')),
                ('scraped_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Scrape')),
            ],
            options={
                'verbose_name': 'Sinta Pengabdian',
                'verbose_name_plural': 'Sinta Pengabdian',
                'ordering': ['-tahun', 'judul'],
            },
        ),
        migrations.CreateModel(
            name='SintaPengabdianAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False, verbose_name='Ketua')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengabdians', to='universities.sintaauthor', verbose_name='Author')),
                ('pengabdian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengabdian_authors', to='universities.sintapengabdian', verbose_name='Pengabdian')),
            ],
            options={
                'verbose_name': 'Sinta Pengabdian Author',
                'verbose_name_plural': 'Sinta Pengabdian Authors',
            },
        ),
        migrations.AddIndex(
            model_name='sintapengabdian',
            index=models.Index(fields=['tahun'], name='universitie_tahun_25ac46_idx'),
        ),
        migrations.AddIndex(
            model_name='sintapengabdian',
            index=models.Index(fields=['skema_kode'], name='universitie_skema_k_1a7ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='sintapengabdian',
            index=models.Index(fields=['sumber'], name='universitie_sumber_a43d96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sintapengabdian',
            unique_together={('judul', 'tahun', 'skema_kode')},
        ),
        migrations.AddIndex(
            model_name='sintapengabdianauthor',
            index=models.Index(fields=['author'], name='universitie_author__d8fdd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sintapengabdianauthor',
            unique_together={('pengabdian', 'author')},
        ),
    ]
