# Generated by Django 4.2.11 on 2026-03-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0021_sinta_pengabdian'),
    ]

    operations = [
        migrations.CreateModel(
            name='KolaboasiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber', models.CharField(default='all', help_text='all | penelitian | pengabdian | scopus', max_length=20)),
                ('min_bobot', models.PositiveSmallIntegerField(default=1, help_text='Bobot edge minimum yang disimpan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Kolaboasi Snapshot',
                'verbose_name_plural': 'Kolaboasi Snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
