# Generated by Django 4.2.11 on 2026-03-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0022_add_kolaboasi_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadosen',
            name='dosen_rasio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datadosen',
            name='rasio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
