# Generated by Django 4.2.11 on 2026-03-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0023_datadosen_dosen_rasio_datadosen_rasio'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstudi',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='ilmu_dipelajari',
            field=models.TextField(blank=True, verbose_name='Ilmu yang Dipelajari'),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='informasi_umum',
            field=models.TextField(blank=True, verbose_name='Informasi Umum'),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='kompetensi',
            field=models.TextField(blank=True, verbose_name='Kompetensi'),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='tanggal_berdiri',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tanggal Berdiri'),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='telepon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telepon'),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website'),
        ),
    ]
