# Generated by Django 4.2.11 on 2026-03-29 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universities', '0024_programstudi_email_programstudi_ilmu_dipelajari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinkronisasiJadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_sync', models.CharField(choices=[('prodi_dosen', 'Prodi + Dosen + Mahasiswa'), ('detail_dosen', 'Detail Dosen')], default='prodi_dosen', max_length=20)),
                ('mode_pt', models.CharField(choices=[('semua', 'Semua PT'), ('pilihan', 'PT Pilihan')], default='semua', max_length=10)),
                ('tipe_jadwal', models.CharField(choices=[('harian', 'Rutin Setiap Hari'), ('sekali', 'Sekali Saja')], default='harian', max_length=10)),
                ('hari_mulai', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], default=0)),
                ('jam_mulai', models.TimeField(default='23:00')),
                ('hari_selesai', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], default=6)),
                ('jam_selesai', models.TimeField(default='05:00')),
                ('is_active', models.BooleanField(default=True)),
                ('status_terakhir', models.CharField(choices=[('menunggu', 'Menunggu'), ('berjalan', 'Sedang Berjalan'), ('selesai', 'Selesai'), ('error', 'Error')], default='menunggu', max_length=10)),
                ('pesan_terakhir', models.TextField(blank=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jadwal', to=settings.AUTH_USER_MODEL)),
                ('pt_list', models.ManyToManyField(blank=True, to='universities.perguruantinggi', verbose_name='PT Pilihan')),
            ],
            options={
                'verbose_name': 'Jadwal Sinkronisasi',
                'verbose_name_plural': 'Jadwal Sinkronisasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
