# Generated by Django 4.2.11 on 2026-03-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0025_sinkronisasijadwal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinkronisasijadwal',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
