# Generated by Django 4.2.11 on 2026-03-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0026_sinkronisasijadwal_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinkronisasijadwal',
            name='sinta_days',
            field=models.IntegerField(default=30, help_text='Scrape ulang author > N hari lalu (0=semua)'),
        ),
        migrations.AddField(
            model_name='sinkronisasijadwal',
            name='sinta_limit',
            field=models.IntegerField(default=500, help_text='Maks. author per run (0=tidak dibatasi)'),
        ),
        migrations.AlterField(
            model_name='sinkronisasijadwal',
            name='tipe_sync',
            field=models.CharField(choices=[('prodi_dosen', 'Prodi + Dosen + Mahasiswa'), ('detail_dosen', 'Detail Dosen'), ('sinta_author', 'SINTA — Author')], default='prodi_dosen', max_length=20),
        ),
    ]
