# Generated by Django 4.2.11 on 2026-06-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0028_sinta_afiliasi_gscholar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datamahasiswa',
            unique_together={('perguruan_tinggi', 'program_studi', 'tahun_akademik', 'semester')},
        ),
    ]
