# Generated by Django 4.2.11 on 2026-06-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0029_rename_univ_affil_gs_art_idx_universitie_afilias_a8a227_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosenSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(db_index=True, max_length=9, verbose_name='Tahun Akademik')),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], db_index=True, max_length=6)),
                ('ikatan_kerja', models.CharField(blank=True, choices=[('tetap', 'Dosen Tetap'), ('tidak_tetap', 'Dosen Tidak Tetap')], max_length=15)),
                ('status', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Dosen Semester',
                'verbose_name_plural': 'Dosen Semester',
            },
        ),
        migrations.AddField(
            model_name='dosensemester',
            name='profil_dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_aktif', to='universities.profildosen', verbose_name='Profil Dosen'),
        ),
        migrations.AddIndex(
            model_name='dosensemester',
            index=models.Index(fields=['tahun_akademik', 'semester'], name='universitie_tahun_a_26c6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='dosensemester',
            index=models.Index(fields=['profil_dosen', 'tahun_akademik', 'semester'], name='universitie_profil__d6b72e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dosensemester',
            unique_together={('profil_dosen', 'tahun_akademik', 'semester')},
        ),
    ]
