# Generated by Django 4.2.11 on 2026-09-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0030_dosensemester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguruantinggi',
            name='akreditasi_institusi',
            field=models.CharField(choices=[('unggul', 'Unggul'), ('baik_sekali', 'Baik Sekali'), ('baik', 'Baik'), ('terakreditasi', 'Terakreditasi'), ('belum', 'Belum Terakreditasi')], default='belum', max_length=20, verbose_name='Akreditasi Institusi'),
        ),
    ]
