# Generated by Django 4.2.11 on 2026-03-12 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriIndikator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Kategori Indikator',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='PeriodePelaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tahun', models.PositiveIntegerField()),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], max_length=10)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif'), ('selesai', 'Selesai'), ('arsip', 'Arsip')], default='draft', max_length=10)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Periode Pelaporan',
                'ordering': ['-tahun', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('info', 'Informasi'), ('warning', 'Peringatan'), ('deadline', 'Tenggat Waktu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], max_length=20)),
                ('judul', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perguruan_tinggi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to='universities.perguruantinggi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaporanPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum', 'Belum Dimulai'), ('draft', 'Draft'), ('submitted', 'Dikirim'), ('review', 'Dalam Review'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='belum', max_length=20)),
                ('persentase_pengisian', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('skor_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('catatan_reviewer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perguruan_tinggi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='universities.perguruantinggi')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laporan', to='monitoring.periodepelaporan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_laporan', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_laporan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laporan PT',
                'ordering': ['-periode__tahun', 'perguruan_tinggi__nama'],
                'unique_together': {('perguruan_tinggi', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='Indikator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('tipe_data', models.CharField(choices=[('angka', 'Angka'), ('persentase', 'Persentase'), ('teks', 'Teks'), ('boolean', 'Ya/Tidak'), ('file', 'File/Dokumen')], max_length=20)),
                ('satuan', models.CharField(blank=True, max_length=50)),
                ('nilai_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nilai_maksimum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nilai_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_wajib', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indikator', to='monitoring.kategoriindikator')),
            ],
            options={
                'verbose_name': 'Indikator',
                'ordering': ['kategori__urutan', 'urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='IsiLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_teks', models.TextField(blank=True)),
                ('nilai_angka', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('nilai_boolean', models.BooleanField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='laporan_files/')),
                ('keterangan', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.indikator')),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isi', to='monitoring.laporanpt')),
            ],
            options={
                'verbose_name': 'Isi Laporan',
                'unique_together': {('laporan', 'indikator')},
            },
        ),
    ]
