# Generated by Django 4.2.11 on 2026-03-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_alter_profildosen_nidn'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('total_pt', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Snapshot Laporan Performa',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotPerPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_prodi', models.IntegerField(default=0)),
                ('prodi_per_jenjang', models.JSONField(default=dict)),
                ('total_dosen', models.IntegerField(default=0)),
                ('dosen_pria', models.IntegerField(default=0)),
                ('dosen_wanita', models.IntegerField(default=0)),
                ('dosen_per_jabatan', models.JSONField(default=dict)),
                ('dosen_per_pendidikan', models.JSONField(default=dict)),
                ('dosen_per_status', models.JSONField(default=dict)),
                ('dosen_per_ikatan', models.JSONField(default=dict)),
                ('mhs_tren', models.JSONField(default=list)),
                ('perguruan_tinggi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.perguruantinggi')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_pt', to='monitoring.snapshotlaporan')),
            ],
            options={
                'ordering': ['perguruan_tinggi__nama'],
                'unique_together': {('snapshot', 'perguruan_tinggi')},
            },
        ),
    ]
