# Generated by Django 4.2.11 on 2026-03-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_snapshot_perpt_flat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotperpt',
            name='dosen_no_detail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snapshotperpt',
            name='dosen_with_detail',
            field=models.IntegerField(default=0),
        ),
    ]
