# Generated by Django 4.2.11 on 2026-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_snapshotperpt_dosen_gender_no_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotlaporan',
            name='semester_dilaporkan',
            field=models.CharField(blank=True, help_text='mis. 2025/2026 Ganjil', max_length=20, verbose_name='Semester Dilaporkan'),
        ),
    ]
